vich_uploader:
    db_driver: orm

    mappings:
        article_cover:
            uri_prefix: /uploads/articles/covers
            upload_destination: '%kernel.project_dir%/public/uploads/articles/covers'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
